### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by DeWildeDaan** [DeWildeDaan/EindopdrachtBD#1]
Als ik via de docker mijn project wil opstarten met 'docker-compose up', starten mijn containers niet en krijg ik volgende output in de terminal:
Error response from daemon: i/o timeout
The terminal process "C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker compose -f "docker-compose.yml" up -d --build" terminated with exit code: 1.

Indien ik de containers handmatig start (want ze worden wel aangemaakt) kan ik mijn api niet bereiken via de browser
![DockerCompose-output](https://user-images.githubusercontent.com/71894656/165920659-056a6722-40c1-446f-98fc-29d8a24c7186.PNG)
.

**Comment by nathansegers** [comment]
Ik kan fout zijn, maar ik denk dat het makkelijker en beter is dat je je Docker-Compose file in je Eindopdracht project steekt.

Indien je dat niet wil, kan je wel je Docker build context verzetten, zo zal je `copy . .` commando beter gaan.

Probeer dat gerust eens.

**Comment by DeWildeDaan** [comment]
Mijn excuses, ik was de aller laatste versie vergeten pushen maar mijn compose staat inderdaar al in mijn eindopdracht project. Ik heb net een push gedaan en ik krijg nog altijd die fout.

**Comment by DeWildeDaan** [comment]
Ik heb ondertussen ook eens wat getest en ik merk dat als ik enkel mijn api service opstart in mijn docker compose file, hij opstart en ik eraan kan. Als ik enkel mijn mongo en mongo-express doe werkt het ook. Maar zowel mijn mongo als api samen werkt dan weer niet.

**Comment by nathansegers** [comment]
Zijn er foutmeldingen die je tegenkomt wanneer je probeert te surfen naar de API?

Voor te testen zou ik wel deze lijn weghalen, dat kan misschien lastig doen bij opstarten.
 
 ​      - ​~/.vsdbg:/remote_debugger:rw

Probeer ook eens met een Named volume in je Mongo database, dat werkt vaak beter.

**Comment by nathansegers** [comment]
Want jouw ./Data mapje zal niet in dockerignore zitten, en dan plaatst die dat ook in de Image, wat heel lang kan duren

**Comment by DeWildeDaan** [comment]
Ik heb de lijn weggehaald en een named volume gebruikt maar krijg nog altijd dezelfde output.
Wanneer ik enkel en alleen men api opstart zonder mongo kan ik eraan zonder foutmeldingen, ik kan dan natuurlijk geen data bevragen want men database werkt niet maar ik geraak zonder fouten aan de swagger documentatie.

![DockerCompose-output](https://user-images.githubusercontent.com/71894656/165925277-6ec637de-14e2-478e-bd63-90ca63eb0f4c.PNG)
t

**Comment by nathansegers** [comment]
En een pc reboot?

**Comment by DeWildeDaan** [comment]
Een pc reboot en update van Docker heeft het inderdaad opgelost, super bedankt voor de hulp!
